[package]
name = "rustmix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
crossbeam = "0"
dotenv = "0"
futures = "0"
rand = "0"
reqwest = { version = "0", features = ["blocking", "cookies", "json", "gzip", "deflate", "multipart", "socks", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.36.0", features = ["full"] }
url = { version = "2", features = ["serde"] }
urlencoding = "2"
rayon = "1"
ua_generator = "0"
lettre = "0"
tempmail = "0"
regex = "1"
once_cell = "1"
chrono = "0"
html-entities = "0"
# pyo3 = { version = "0", features = ["auto-initialize"] }

[package.metadata.scripts]
run = "cargo run"
check = "cargo check"
build = "cargo build"
release = "cargo build --release"
features = "cargo feature %1"
