[package]
name = "rustmix"
version = "0.1.0"
edition = "2021"

[features]
default = []
mail = ["html-entities", "lettre", "tempmail", "once_cell"]
python = ["pyo3"]
ai = []
whisper = ["kalosm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
crossbeam = "0"
dotenv = "0"
futures = "0"
rand = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.36.0", features = ["full"] }
regex = "1"
once_cell = { version = "1", optional = true }
rayon = "1"
chrono = "0"
anyhow = "1"
html-entities = { version = "0", optional = true }
lettre = { version = "0", optional = true }
ua_generator = "0"
url = { version = "2", features = ["serde"] }
urlencoding = "2"
reqwest = { version = "0", features = ["blocking", "cookies", "json", "gzip", "deflate", "multipart", "socks", "stream"] }
tempmail = { version = "1", optional = true }
pyo3 = { version = "0", features = ["auto-initialize", "abi3", "hashbrown", "indexmap", "serde", "smallvec"], optional = true }
kalosm = { version = "0", optional = true }

[package.metadata.scripts]
run = "cargo run"
check = "cargo check"
build = "cargo build"
release = "cargo build --release"
features = "cargo feature %1"
