[package]
name = "rustmix"
version = "0.1.0"
edition = "2021"

[features]
default = ["mail", "threading", "log-log4rs", "log-slog"]
mail = ["html-entities", "lettre", "tempmail", "once_cell", "regex"]
python = ["pyo3"]
whisper = ["kalosm"]
threading = ["crossbeam", "rayon"]
log-slog = ["slog", "slog-config", "slog-term", "slog-stdlog", "slog-async", "slog-scope", "file-rotate"]
log-log4rs = ["log4rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
crossbeam = { version = "0", optional = true }
dotenv = "0"
futures = "0"
rand = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.36.0", features = ["full"] }
regex = { version = "1", optional = true }
once_cell = { version = "1", optional = true }
rayon = { version = "1", optional = true }
chrono = "0"
anyhow = "1"
html-entities = { version = "0", optional = true }
lettre = { version = "0", optional = true }
ua_generator = "0"
url = { version = "2", features = ["serde"] }
urlencoding = "2"
reqwest = { version = "0", features = ["blocking", "cookies", "json", "gzip", "deflate", "multipart", "socks", "stream"] }
tempmail = { version = "1", optional = true }
pyo3 = { version = "0", features = ["auto-initialize", "abi3", "hashbrown", "indexmap", "serde", "smallvec"], optional = true }
kalosm = { version = "0", optional = true }
log = "0"
slog = { version = "2", optional = true }
slog-config = { version = "0", optional = true }
slog-term = { version = "2", optional = true }
slog-stdlog = { version = "4", optional = true }
slog-async = { version = "2", optional = true }
slog-scope = { version = "4", optional = true }
file-rotate = { version = "0", optional = true }
log4rs = { version = "1", optional = true }

[package.metadata.scripts]
run = "cargo run"
check = "cargo check"
build = "cargo build"
release = "cargo build --release"
features = "cargo tree --features"
