[package]
name = "kalosm-learning-macro"
version = "0.3.2"
edition = "2021"
description = "A macro to derive kalosm learning traits"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff"]
keywords = ["ai", "bert", "nlp", "machine-learning", "transformers"]

[dependencies]
syn = "2"
quote = "1"

[lib]
proc-macro = true
